# Generated by Django 6.0 on 2025-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='subTotal',
            new_name='sub_total',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('CONFIRMED', 'Confirmed'), ('delivered', 'DELIVERED')], default='PENDING', max_length=20),
        ),
    ]
