# Generated by Django 6.0 on 2025-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'delivered')], default='PENDING', max_length=20),
        ),
    ]
